#!/bin/bash
systemctl stop caddy.service
cd /tmp
xcaddy build \
    --with github.com/mholt/caddy-events-exec \
    --with github.com/greenpau/caddy-security
mv caddy /usr/bin
systemctl start caddy.service
